# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Get the coverage
        run: |
          set -x
          VALUE=90

          if (( $(echo "$VALUE <= 50" | bc -l) )); then
            COLOR=red
          elif (( $(echo "$VALUE > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          echo "COLOR=$COLOR" >> $GITHUB_ENV
          echo "VALUE=$VALUE" >> $GITHUB_ENV
          echo ${{ github.event.repository.name }}
      - name: set coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.COVERAGE_TOKEN }}
          gistID: 277c7acb9222d5762a31958b394afb2f
          filename: ${{ github.event.repository.name }}-coverage.json
          label: coverage
          message: ${{ env.VALUE }}
          color: ${{ env.COLOR }}
